---

## Note: script used below is using local-data command to redirect to another IP
## alternative option is inform_deny eg 'local-zone: "google.com" inform_deny.'
## https://github.com/Aracktus/DNS-Unbound-Blocklist-Downloader
## https://github.com/aabed/DNSblacklist
## http://www.shellguardians.com/2016/08/building-dns-sinkhole-in-freebsd-with.html
## https://cyprio.net/wtf/2014-06-22-unbound-catch-all.html

- name: Ensure script directory exists
  file:
    dest: "{{ scriptsdir }}"
    mode: '0755'
    state: directory

- name: check if script exists
  stat: path="{{ scriptsdir }}/dns-unbound-blocklist-downloader.py"
  register: havescript
- name: download domains feed script
  get_url:
    url: "{% if ansible_python_interpreter == 'python3' %}https://github.com/juju4/DNS-Unbound-Blocklist-Downloader/raw/master/dns-unbound-blocklist-downloader.py{% else %}https://raw.githubusercontent.com/juju4/DNS-Unbound-Blocklist-Downloader/3782d61dab1ca44b95327ea89319a91189e67960/dns-unbound-blocklist-downloader.py{% endif %}"
    dest: "{{ scriptsdir }}/dns-unbound-blocklist-downloader.py"
    checksum: "{% if ansible_python_interpreter == 'python3' %}sha256:12ff8e1b08f49109b483c8789f48c766ccd65c852380dcc6434b31478d62f07b{% else %}1582b5301a6e0b13b6f93555b7f2452b6f3cc38d625cc471cbdbbf7a314ab0f7{% endif %}"
    mode: 0755
  when: not havescript.stat.exists

- name: update blackhole script configuration
  replace:
    dest: "{{ scriptsdir }}/dns-unbound-blocklist-downloader.py"
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    backup: yes
  with_items:
    - { re: "^location = '/etc/unbound/'", rep: "location = '/etc/unbound/conf.d/'" }
    - { re: "^filename = 'local-blocking-data.conf'", rep: "filename = '80local-blocking-data.conf'" }
    - { re: "^IPV4_ADDR = '.*'", rep: "IPV4_ADDR = '{{ unbound_sinkhole_ipv4 }}'" }
    - { re: "^IPV6_ADDR = '.*'", rep: "IPV6_ADDR = '{{ unbound_sinkhole_ipv6 }}'" }

- name: run blackhole feed script first time
  command: >
    {{ ansible_python_interpreter | default('python') }} {{ scriptsdir }}/dns-unbound-blocklist-downloader.py
  args:
    creates: /etc/unbound/conf.d/80local-blocking-data.conf
  notify: restart unbound

- name: debian | ensure crontab is present
  package: name=cron state=present
  when: ansible_os_family == "Debian"
  register: pkg_result
  until: pkg_result is success

- name: redhat | ensure crontab is present
  package: name=crontabs state=present
  when: ansible_os_family == "RedHat"
  register: pkg_result
  until: pkg_result is success

- name: add update feed cron task
  cron:
    name: "unbound blackhole update"
    minute: '35'
    hour: '3'
    user: "root"
    job: "{{ scriptsdir }}/dns-unbound-blocklist-downloader.py -r > /tmp/dns-unbound-blocklist-downloader.out 2>&1"
    cron_file: ansible_unbound-blackhole-update

- name: add blackholing of known bad TLDs
  template:
    src: 80blackhole_zone.conf.j2
    dest: /etc/unbound/conf.d/80blackhole_zone.conf
    mode: '0644'
# ubuntu: unbound-checkconf[606:0] fatal error: config file /root/.ansible/tmp/ansible-tmp-xxx/source
#        is not inside chroot /etc/unbound
#    validate: "/usr/sbin/unbound-checkconf %s"
  notify: restart unbound
